name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "14.X"
      - name: Install deps
        run: npm install
      
      - name: Build VitePress
        run: npm run build

     # push actions
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
          # preserve old hash files, only when docs change, display commit message
          # defalt true, will automatically delete files
          clean: false
          # default true, will force-push and overwrite existing deployment
          force: false